app = 'isaac-tracker'
primary_region = 'fra'

[build]
  dockerfile = 'server/Dockerfile'

[env]
  PORT = '3000'

[[services]]
  internal_port = 3000
  protocol = 'tcp'
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    force_https = true
    handlers = ['http']
    port = 80

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
